# Generated by Django 3.1.2 on 2020-10-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
